### PR TITLE
Stage -> Prod Sync (May 2024 Release)

### PR DESCRIPTION
**Pull request by we-ai**
Issues Addressed:
- Fix empty string bugs described in [issue #979](https://github.com/episphere/connect/issues/979) and [issue #976](https://github.com/episphere/connect/issues/976) (@we-ai)
- https://github.com/episphere/connect/issues/944 (@jhflorey)
- https://github.com/episphere/connect/issues/996 (@jhflorey)
- [BSWH dev SSO window login](https://github.com/episphere/dashboard/pull/653), related to [issue #884](https://github.com/episphere/connect/issues/884) (@Gbarra9)
- https://github.com/episphere/connect/issues/941 (@bransteitterbr)

### CODE REVIEW

**Comment by we-ai** [comment]
My updates (bug fixes) are tested in stage, and are ready for prod.

**Review by Gbarra9 — APPROVED** [review]
My change is dev related and was not tested in stage.

**Review by bransteitterbr — APPROVED** [review]

**Comment by bransteitterbr** [comment]
Ready for Prod

**Review by jhflorey — APPROVED** [review]

**Comment by jhflorey** [comment]
My changes are ready for prod

**Pull request merged**
