### PR TITLE
Stage -> Prod Sync (Aug. Release)

### PR DESCRIPTION
**Pull request by we-ai**
Issues Addressed:
- https://github.com/episphere/connectApp/issues/537. Further updates (@jhflorey)
- https://github.com/episphere/connect/issues/694 (@bransteitterbr)
- https://github.com/episphere/connect/issues/669. Added new variables (@abhinavjonnada82)

### CODE REVIEW

**Comment by abhinavjonnada82** [comment]
Looks good

**Comment by jhflorey** [comment]
Tested and ready for prod - https://github.com/episphere/connectApp/issues/537#issuecomment-1703103379

**Comment by abhinavjonnada82** [comment]
Looks good & can move forward.

**Comment by bransteitterbr** [comment]
Tested and Ready

**Pull request merged**
