### PR TITLE
Dev -> Stage Sync (May 2024 Release)

### PR DESCRIPTION
**Pull request by we-ai**
Issues Addressed:
- Fix empty string bugs described in [issue #979](https://github.com/episphere/connect/issues/979) and [issue #976](https://github.com/episphere/connect/issues/976) (@we-ai)
- https://github.com/episphere/connect/issues/944 (@jhflorey)
- https://github.com/episphere/connect/issues/996 (@jhflorey)
- [BSWH dev SSO window login](https://github.com/episphere/dashboard/pull/653), related to [issue #884](https://github.com/episphere/connect/issues/884) (@Gbarra9)
- https://github.com/episphere/connect/issues/941 (@bransteitterbr)

### CODE REVIEW

**Comment by we-ai** [comment]
Ready for stage.

**Comment by jhflorey** [comment]
My changes are ready for stage

**Review by jhflorey — APPROVED** [review]

**Review by bransteitterbr — APPROVED** [review]

**Comment by bransteitterbr** [comment]
Ready for stage

**Review by Gbarra9 — APPROVED** [review]
Changes are dev related only. SSO window was tested by someone from BSWH. BSWH is currently setting up their active directory groups.

**Pull request merged**
