### PR TITLE
Dev -> Stage Sync (June 2024)

### PR DESCRIPTION
**Pull request by anthonypetersen**
Issues Addressed
-----
* https://github.com/episphere/connect/issues/884 - @Gbarra9 
* https://github.com/episphere/connect/issues/918 - @we-ai 
* https://github.com/episphere/connect/issues/915 - @amber-emmes 
* https://github.com/episphere/connect/issues/1035 - @Gbarra9 
* https://github.com/episphere/connect/issues/1036 - @anthonypetersen

### CODE REVIEW

**Comment by amber-emmes** [comment]
[915](https://github.com/episphere/connect/issues/915) tested and ready for stage.

**Review by amber-emmes — APPROVED** [review]

**Comment by we-ai** [comment]
My updates are ready for stage.

**Review by we-ai — APPROVED** [review]

**Review by Gbarra9 — APPROVED** [review]
My updates are ready for stage

**Comment by anthonypetersen** [comment]
ready for stage

**Pull request merged**
